In [3]:
from nsepy import get_history as gh
import datetime as dt # 1 hr data only not less than that.
import yfinance as yf

In [4]:
start = dt.datetime(2013,1,1)
end = dt.datetime(2023,1,1)
stk_data = yf.download("RELIANCE.NS", start=start, end=end)

[*********************100%***********************]  1 of 1 completed

In [6]:
stk_data

Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2013-01-01   176.018585   177.253884   175.683586   176.709519     6831351
2013-01-02   177.536530   179.221978   176.405928   176.709522    13441898
2013-01-03   180.216476   180.478183   176.835126   177.672602    17266808
2013-01-04   180.446793   181.022562   178.709017   180.457261    13306377
2013-01-07   179.347565   182.362511   178.342583   181.252846    15307180
...                 ...          ...          ...          ...         ...
2022-12-26  1152.220215  1160.414342  1137.772122  1147.974874     5990242
2022-12-27  1161.646851  1163.518428  1148.203010  1154.936341     5763271
2022-12-28  1161.532837  1163.975064  1151.056230  1158.588423     7459393
2022-12-29  1161.007935  1163.564268  1152.882270  1153.567026     6930648
2022-12-30  1162.788086  1176.391675  1160.003541  1161.829476     7289476

[2468 rows x 5 columns]

In [7]:
dataset=stk_data
dataset.columns

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS')],
           names=['Price', 'Ticker'])

In [8]:
dataset.columns = dataset.columns.get_level_values(0)
dataset.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

In [9]:
ohlc = stk_data[["Open", "High", "Low", "Close"]]
ohlc

Price              Open         High          Low        Close
Date
2013-01-01   176.709519   177.253884   175.683586   176.018585
2013-01-02   176.709522   179.221978   176.405928   177.536530
2013-01-03   177.672602   180.478183   176.835126   180.216476
2013-01-04   180.457261   181.022562   178.709017   180.446793
2013-01-07   181.252846   182.362511   178.342583   179.347565
...                 ...          ...          ...          ...
2022-12-26  1147.974874  1160.414342  1137.772122  1152.220215
2022-12-27  1154.936341  1163.518428  1148.203010  1161.646851
2022-12-28  1158.588423  1163.975064  1151.056230  1161.532837
2022-12-29  1153.567026  1163.564268  1152.882270  1161.007935
2022-12-30  1161.829476  1176.391675  1160.003541  1162.788086

[2468 rows x 4 columns]

In [10]:
ohlc.index.name = "Date"

In [11]:
ohlc.to_csv("reliance_ohlc2.csv")

In [12]:
#importing the dataset
import pandas as pd
dataset = pd.read_csv("reliance_ohlc2.csv",parse_dates=['Date'],index_col='Date')
dataset

                   Open         High          Low        Close
Date
2013-01-01   176.709519   177.253884   175.683586   176.018585
2013-01-02   176.709522   179.221978   176.405928   177.536530
2013-01-03   177.672602   180.478183   176.835126   180.216476
2013-01-04   180.457261   181.022562   178.709017   180.446793
2013-01-07   181.252846   182.362511   178.342583   179.347565
...                 ...          ...          ...          ...
2022-12-26  1147.974874  1160.414342  1137.772122  1152.220215
2022-12-27  1154.936341  1163.518428  1148.203010  1161.646851
2022-12-28  1158.588423  1163.975064  1151.056230  1161.532837
2022-12-29  1153.567026  1163.564268  1152.882270  1161.007935
2022-12-30  1161.829476  1176.391675  1160.003541  1162.788086

[2468 rows x 4 columns]

In [16]:
#Start date and end_date, converting the "2013-01-01" into timestap object using to_datetime
from datetime import date, timedelta
import pandas as pd
start_date = pd.to_datetime("2013-01-01")
#timedelta used to add /subtract the days, here we excluding last
end_date = pd.to_datetime("2023-01-01") - timedelta(days=1) 
#data_range creates a continuous sequence of dates. Here freq='d' means daily frequency including weekends and holidays.
all_date = pd.date_range(start_date, end_date, freq='d')

In [17]:
all_date

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=3652, freq='D')

In [21]:
#Here we connectig the dataset with sequence dates
dummyDate = dataset
dummyDate.index = all_date
dummyDate

ValueError: Length mismatch: Expected axis has 2468 elements, new values have 3652 elements